htr:
  max_threads: 1
  # charset_path: ${}
  model:
    model_path: ${weights_path:recognizer.script}
    device: "cpu"
#"cuda:0"

sentry:
    dsn: "https://3c0bc8764cdd4d7f87b9a198f746cfcf@o971997.ingest.sentry.io/5924413"